# Generated by Django 5.2.8 on 2025-11-17 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('LOCATION_HEAD', 'Location Head'), ('STOCK_INCHARGE', 'Stock Incharge'), ('AUDITOR', 'Auditor')], max_length=20)),
                ('permissions', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['role'], name='user_manage_role_363543_idx'), models.Index(fields=['name'], name='user_manage_name_7f8086_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE_USER', 'Create User'), ('UPDATE_USER', 'Update User'), ('DELETE_USER', 'Delete User'), ('CREATE_LOCATION', 'Create Location'), ('UPDATE_LOCATION', 'Update Location'), ('DELETE_LOCATION', 'Delete Location'), ('CREATE_ITEM', 'Create Item'), ('UPDATE_ITEM', 'Update Item'), ('DELETE_ITEM', 'Delete Item'), ('CREATE_INSPECTION_CERTIFICATE', 'Create Inspection Certificate'), ('UPDATE_INSPECTION_CERTIFICATE', 'Update Inspection Certificate'), ('STOCK_ENTRY', 'Stock Entry'), ('INSTANCE_MOVEMENT', 'Instance Movement'), ('ACKNOWLEDGE_TRANSFER', 'Acknowledge Transfer'), ('GENERATE_QR_CODE', 'Generate QR Code'), ('UPWARD_TRANSFER', 'Upward Transfer to Parent Standalone')], max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='user_manage_created_a3f933_idx'), models.Index(fields=['user', '-created_at'], name='user_manage_user_id_6270cd_idx'), models.Index(fields=['action'], name='user_manage_action_feb4c2_idx'), models.Index(fields=['model'], name='user_manage_model_2c89b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('LOCATION_HEAD', 'Location Head'), ('STOCK_INCHARGE', 'Stock Incharge'), ('AUDITOR', 'Auditor')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('custom_permissions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_locations', models.ManyToManyField(blank=True, help_text='Locations this user is directly assigned to manage', related_name='assigned_users', to='inventory.location')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_users', to='inventory.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['role'], name='user_manage_role_49e144_idx'), models.Index(fields=['employee_id'], name='user_manage_employe_0bdeec_idx'), models.Index(fields=['is_active'], name='user_manage_is_acti_67547c_idx')],
            },
        ),
    ]
