# Generated by Django 5.2.8 on 2025-11-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='depreciation_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Annual depreciation rate in percentage (e.g., 10.00 for 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='purchase_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original purchase value/cost', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='inspectioncertificate',
            name='rejection_stage',
            field=models.CharField(blank=True, choices=[('INITIATED', 'Initiated - Basic Info'), ('STOCK_DETAILS', 'Stock Details Entry'), ('CENTRAL_REGISTER', 'Central Register Entry'), ('AUDIT_REVIEW', 'Audit Review'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inspectioncertificate',
            name='stage',
            field=models.CharField(choices=[('INITIATED', 'Initiated - Basic Info'), ('STOCK_DETAILS', 'Stock Details Entry'), ('CENTRAL_REGISTER', 'Central Register Entry'), ('AUDIT_REVIEW', 'Audit Review'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='INITIATED', max_length=20),
        ),
    ]
